/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AvaliacaoRouteImport } from './routes/avaliacao'
import { Route as ComunidadeRouteImport } from './routes/comunidade'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DepoimentoRouteImport } from './routes/depoimento'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PosCompraRouteImport } from './routes/pos-compra'
import { Route as RelatorioPdfRouteImport } from './routes/relatorio-pdf'
import { Route as RelatorioOnlineRouteImport } from './routes/relatorio-online'
import { Route as LeituraTrajetoriaRouteImport } from './routes/leitura-trajetoria'
import { Route as LeituraTrajetoriaOfertaRouteImport } from './routes/leitura-trajetoria-oferta'
import { Route as CheckoutOfferIdRouteImport } from './routes/checkout.$offerId'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AvaliacaoRoute = AvaliacaoRouteImport.update({
  id: '/avaliacao',
  path: '/avaliacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunidadeRoute = ComunidadeRouteImport.update({
  id: '/comunidade',
  path: '/comunidade',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DepoimentoRoute = DepoimentoRouteImport.update({
  id: '/depoimento',
  path: '/depoimento',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PosCompraRoute = PosCompraRouteImport.update({
  id: '/pos-compra',
  path: '/pos-compra',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatorioPdfRoute = RelatorioPdfRouteImport.update({
  id: '/relatorio-pdf',
  path: '/relatorio-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatorioOnlineRoute = RelatorioOnlineRouteImport.update({
  id: '/relatorio-online',
  path: '/relatorio-online',
  getParentRoute: () => rootRouteImport,
} as any)
const LeituraTrajetoriaRoute = LeituraTrajetoriaRouteImport.update({
  id: '/leitura-trajetoria',
  path: '/leitura-trajetoria',
  getParentRoute: () => rootRouteImport,
} as any)
const LeituraTrajetoriaOfertaRoute = LeituraTrajetoriaOfertaRouteImport.update({
  id: '/leitura-trajetoria-oferta',
  path: '/leitura-trajetoria-oferta',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutOfferIdRoute = CheckoutOfferIdRouteImport.update({
  id: '/checkout/$offerId',
  path: '/checkout/$offerId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRoute
  '/': typeof IndexRoute
  '/avaliacao': typeof AvaliacaoRoute
  '/comunidade': typeof ComunidadeRoute
  '/dashboard': typeof DashboardRoute
  '/depoimento': typeof DepoimentoRoute
  '/login': typeof LoginRoute
  '/pos-compra': typeof PosCompraRoute
  '/relatorio-pdf': typeof RelatorioPdfRoute
  '/relatorio-online': typeof RelatorioOnlineRoute
  '/leitura-trajetoria-oferta': typeof LeituraTrajetoriaOfertaRoute
  '/checkout/$offerId': typeof CheckoutOfferIdRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminRoute
  '/': typeof IndexRoute
  '/avaliacao': typeof AvaliacaoRoute
  '/comunidade': typeof ComunidadeRoute
  '/dashboard': typeof DashboardRoute
  '/depoimento': typeof DepoimentoRoute
  '/login': typeof LoginRoute
  '/pos-compra': typeof PosCompraRoute
  '/relatorio-pdf': typeof RelatorioPdfRoute
  '/leitura-trajetoria-oferta': typeof LeituraTrajetoriaOfertaRoute
  '/checkout/$offerId': typeof CheckoutOfferIdRoute
}
export interface FileRoutesById {
  '/admin': typeof AdminRoute
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/avaliacao': typeof AvaliacaoRoute
  '/comunidade': typeof ComunidadeRoute
  '/dashboard': typeof DashboardRoute
  '/depoimento': typeof DepoimentoRoute
  '/login': typeof LoginRoute
  '/pos-compra': typeof PosCompraRoute
  '/relatorio-pdf': typeof RelatorioPdfRoute
  '/leitura-trajetoria-oferta': typeof LeituraTrajetoriaOfertaRoute
  '/checkout/$offerId': typeof CheckoutOfferIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/'
    | '/avaliacao'
    | '/comunidade'
    | '/dashboard'
    | '/depoimento'
    | '/login'
    | '/pos-compra'
    | '/relatorio-pdf'
    | '/relatorio-online'
    | '/leitura-trajetoria-oferta'
    | '/checkout/$offerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/'
    | '/avaliacao'
    | '/comunidade'
    | '/dashboard'
    | '/depoimento'
    | '/login'
    | '/pos-compra'
    | '/relatorio-pdf'
    | '/leitura-trajetoria-oferta'
    | '/checkout/$offerId'
  id:
    | '__root__'
    | '/admin'
    | '/'
    | '/avaliacao'
    | '/comunidade'
    | '/dashboard'
    | '/depoimento'
    | '/login'
    | '/pos-compra'
    | '/relatorio-pdf'
    | '/leitura-trajetoria-oferta'
    | '/checkout/$offerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRoute
  IndexRoute: typeof IndexRoute
  AvaliacaoRoute: typeof AvaliacaoRoute
  ComunidadeRoute: typeof ComunidadeRoute
  DashboardRoute: typeof DashboardRoute
  DepoimentoRoute: typeof DepoimentoRoute
  LoginRoute: typeof LoginRoute
  PosCompraRoute: typeof PosCompraRoute
  RelatorioPdfRoute: typeof RelatorioPdfRoute
  RelatorioOnlineRoute: typeof RelatorioOnlineRoute
  LeituraTrajetoriaRoute: typeof LeituraTrajetoriaRoute
  LeituraTrajetoriaOfertaRoute: typeof LeituraTrajetoriaOfertaRoute
  CheckoutOfferIdRoute: typeof CheckoutOfferIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avaliacao': {
      id: '/avaliacao'
      path: '/avaliacao'
      fullPath: '/avaliacao'
      preLoaderRoute: typeof AvaliacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidade': {
      id: '/comunidade'
      path: '/comunidade'
      fullPath: '/comunidade'
      preLoaderRoute: typeof ComunidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/depoimento': {
      id: '/depoimento'
      path: '/depoimento'
      fullPath: '/depoimento'
      preLoaderRoute: typeof DepoimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos-compra': {
      id: '/pos-compra'
      path: '/pos-compra'
      fullPath: '/pos-compra'
      preLoaderRoute: typeof PosCompraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorio-pdf': {
      id: '/relatorio-pdf'
      path: '/relatorio-pdf'
      fullPath: '/relatorio-pdf'
      preLoaderRoute: typeof RelatorioPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorio-online': {
      id: '/relatorio-online'
      path: '/relatorio-online'
      fullPath: '/relatorio-online'
      preLoaderRoute: typeof RelatorioOnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leitura-trajetoria': {
      id: '/leitura-trajetoria'
      path: '/leitura-trajetoria'
      fullPath: '/leitura-trajetoria'
      preLoaderRoute: typeof LeituraTrajetoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leitura-trajetoria-oferta': {
      id: '/leitura-trajetoria-oferta'
      path: '/leitura-trajetoria-oferta'
      fullPath: '/leitura-trajetoria-oferta'
      preLoaderRoute: typeof LeituraTrajetoriaOfertaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$offerId': {
      id: '/checkout/$offerId'
      path: '/checkout/$offerId'
      fullPath: '/checkout/$offerId'
      preLoaderRoute: typeof CheckoutOfferIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRoute,
  IndexRoute: IndexRoute,
  AvaliacaoRoute: AvaliacaoRoute,
  ComunidadeRoute: ComunidadeRoute,
  DashboardRoute: DashboardRoute,
  DepoimentoRoute: DepoimentoRoute,
  LoginRoute: LoginRoute,
  PosCompraRoute: PosCompraRoute,
  RelatorioPdfRoute: RelatorioPdfRoute,
  RelatorioOnlineRoute: RelatorioOnlineRoute,
  LeituraTrajetoriaRoute: LeituraTrajetoriaRoute,
  LeituraTrajetoriaOfertaRoute: LeituraTrajetoriaOfertaRoute,
  CheckoutOfferIdRoute: CheckoutOfferIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
