/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AvaliacaoRouteImport } from './routes/avaliacao'
import { Route as ComunidadeRouteImport } from './routes/comunidade'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DepoimentoRouteImport } from './routes/depoimento'
import { Route as LeituraTrajetoriaRouteImport } from './routes/leitura-trajetoria'
import { Route as LeituraTrajetoriaOfertaRouteImport } from './routes/leitura-trajetoria-oferta'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PosCompraRouteImport } from './routes/pos-compra'
import { Route as RelatorioOnlineRouteImport } from './routes/relatorio-online'
import { Route as RelatorioPdfRouteImport } from './routes/relatorio-pdf'
import { Route as CheckoutOfferIdRouteImport } from './routes/checkout.$offerId'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as ConteudosRouteImport } from './routes/conteudos'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as AjudaRouteImport } from './routes/ajuda'
import { Route as PropositoRouteImport } from './routes/proposito'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AvaliacaoRoute = AvaliacaoRouteImport.update({
  id: '/avaliacao',
  path: '/avaliacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunidadeRoute = ComunidadeRouteImport.update({
  id: '/comunidade',
  path: '/comunidade',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DepoimentoRoute = DepoimentoRouteImport.update({
  id: '/depoimento',
  path: '/depoimento',
  getParentRoute: () => rootRouteImport,
} as any)
const LeituraTrajetoriaRoute = LeituraTrajetoriaRouteImport.update({
  id: '/leitura-trajetoria',
  path: '/leitura-trajetoria',
  getParentRoute: () => rootRouteImport,
} as any)
const LeituraTrajetoriaOfertaRoute = LeituraTrajetoriaOfertaRouteImport.update({
  id: '/leitura-trajetoria-oferta',
  path: '/leitura-trajetoria-oferta',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PosCompraRoute = PosCompraRouteImport.update({
  id: '/pos-compra',
  path: '/pos-compra',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatorioOnlineRoute = RelatorioOnlineRouteImport.update({
  id: '/relatorio-online',
  path: '/relatorio-online',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatorioPdfRoute = RelatorioPdfRouteImport.update({
  id: '/relatorio-pdf',
  path: '/relatorio-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const ConteudosRoute = ConteudosRouteImport.update({
  id: '/conteudos',
  path: '/conteudos',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const AjudaRoute = AjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => rootRouteImport,
} as any)
const PropositoRoute = PropositoRouteImport.update({
  id: '/proposito',
  path: '/proposito',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutOfferIdRoute = CheckoutOfferIdRouteImport.update({
  id: '/checkout/$offerId',
  path: '/checkout/$offerId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/avaliacao': typeof AvaliacaoRoute
  '/comunidade': typeof ComunidadeRoute
  '/dashboard': typeof DashboardRoute
  '/depoimento': typeof DepoimentoRoute
  '/leitura-trajetoria': typeof LeituraTrajetoriaRoute
  '/leitura-trajetoria-oferta': typeof LeituraTrajetoriaOfertaRoute
  '/login': typeof LoginRoute
  '/pos-compra': typeof PosCompraRoute
  '/relatorio-online': typeof RelatorioOnlineRoute
  '/relatorio-pdf': typeof RelatorioPdfRoute
  '/checkout/$offerId': typeof CheckoutOfferIdRoute
  '/conta': typeof ContaRoute
  '/conteudos': typeof ConteudosRoute
  '/videos': typeof VideosRoute
  '/sobre': typeof SobreRoute
  '/ajuda': typeof AjudaRoute
  '/proposito': typeof PropositoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/avaliacao': typeof AvaliacaoRoute
  '/comunidade': typeof ComunidadeRoute
  '/dashboard': typeof DashboardRoute
  '/depoimento': typeof DepoimentoRoute
  '/leitura-trajetoria': typeof LeituraTrajetoriaRoute
  '/leitura-trajetoria-oferta': typeof LeituraTrajetoriaOfertaRoute
  '/login': typeof LoginRoute
  '/pos-compra': typeof PosCompraRoute
  '/relatorio-online': typeof RelatorioOnlineRoute
  '/relatorio-pdf': typeof RelatorioPdfRoute
  '/checkout/$offerId': typeof CheckoutOfferIdRoute
  '/conta': typeof ContaRoute
  '/conteudos': typeof ConteudosRoute
  '/videos': typeof VideosRoute
  '/sobre': typeof SobreRoute
  '/ajuda': typeof AjudaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/avaliacao': typeof AvaliacaoRoute
  '/comunidade': typeof ComunidadeRoute
  '/dashboard': typeof DashboardRoute
  '/depoimento': typeof DepoimentoRoute
  '/leitura-trajetoria': typeof LeituraTrajetoriaRoute
  '/leitura-trajetoria-oferta': typeof LeituraTrajetoriaOfertaRoute
  '/login': typeof LoginRoute
  '/pos-compra': typeof PosCompraRoute
  '/relatorio-online': typeof RelatorioOnlineRoute
  '/relatorio-pdf': typeof RelatorioPdfRoute
  '/checkout/$offerId': typeof CheckoutOfferIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/avaliacao'
    | '/comunidade'
    | '/dashboard'
    | '/depoimento'
    | '/leitura-trajetoria'
    | '/leitura-trajetoria-oferta'
    | '/login'
    | '/pos-compra'
    | '/relatorio-online'
    | '/relatorio-pdf'
    | '/checkout/$offerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/avaliacao'
    | '/comunidade'
    | '/dashboard'
    | '/depoimento'
    | '/leitura-trajetoria'
    | '/leitura-trajetoria-oferta'
    | '/login'
    | '/pos-compra'
    | '/relatorio-online'
    | '/relatorio-pdf'
    | '/checkout/$offerId'
    | '/conta'
    | '/conteudos'
    | '/videos'
    | '/sobre'
    | '/ajuda'
    | '/proposito'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/avaliacao'
    | '/comunidade'
    | '/dashboard'
    | '/depoimento'
    | '/leitura-trajetoria'
    | '/leitura-trajetoria-oferta'
    | '/login'
    | '/pos-compra'
    | '/relatorio-online'
    | '/relatorio-pdf'
    | '/checkout/$offerId'
    | '/conta'
    | '/conteudos'
    | '/videos'
    | '/sobre'
    | '/ajuda'
    | '/proposito'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AvaliacaoRoute: typeof AvaliacaoRoute
  ComunidadeRoute: typeof ComunidadeRoute
  DashboardRoute: typeof DashboardRoute
  DepoimentoRoute: typeof DepoimentoRoute
  LeituraTrajetoriaRoute: typeof LeituraTrajetoriaRoute
  LeituraTrajetoriaOfertaRoute: typeof LeituraTrajetoriaOfertaRoute
  LoginRoute: typeof LoginRoute
  PosCompraRoute: typeof PosCompraRoute
  RelatorioOnlineRoute: typeof RelatorioOnlineRoute
  RelatorioPdfRoute: typeof RelatorioPdfRoute
  CheckoutOfferIdRoute: typeof CheckoutOfferIdRoute
  ContaRoute: typeof ContaRoute
  ConteudosRoute: typeof ConteudosRoute
  VideosRoute: typeof VideosRoute
  SobreRoute: typeof SobreRoute
  AjudaRoute: typeof AjudaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avaliacao': {
      id: '/avaliacao'
      path: '/avaliacao'
      fullPath: '/avaliacao'
      preLoaderRoute: typeof AvaliacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidade': {
      id: '/comunidade'
      path: '/comunidade'
      fullPath: '/comunidade'
      preLoaderRoute: typeof ComunidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/depoimento': {
      id: '/depoimento'
      path: '/depoimento'
      fullPath: '/depoimento'
      preLoaderRoute: typeof DepoimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leitura-trajetoria': {
      id: '/leitura-trajetoria'
      path: '/leitura-trajetoria'
      fullPath: '/leitura-trajetoria'
      preLoaderRoute: typeof LeituraTrajetoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leitura-trajetoria-oferta': {
      id: '/leitura-trajetoria-oferta'
      path: '/leitura-trajetoria-oferta'
      fullPath: '/leitura-trajetoria-oferta'
      preLoaderRoute: typeof LeituraTrajetoriaOfertaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos-compra': {
      id: '/pos-compra'
      path: '/pos-compra'
      fullPath: '/pos-compra'
      preLoaderRoute: typeof PosCompraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorio-online': {
      id: '/relatorio-online'
      path: '/relatorio-online'
      fullPath: '/relatorio-online'
      preLoaderRoute: typeof RelatorioOnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorio-pdf': {
      id: '/relatorio-pdf'
      path: '/relatorio-pdf'
      fullPath: '/relatorio-pdf'
      preLoaderRoute: typeof RelatorioPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$offerId': {
      id: '/checkout/$offerId'
      path: '/checkout/$offerId'
      fullPath: '/checkout/$offerId'
      preLoaderRoute: typeof CheckoutOfferIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudos': {
      id: '/conteudos'
      path: '/conteudos'
      fullPath: '/conteudos'
      preLoaderRoute: typeof ConteudosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuda': {
      id: '/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AjudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposito': {
      id: '/proposito'
      path: '/proposito'
      fullPath: '/proposito'
      preLoaderRoute: typeof PropositoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AvaliacaoRoute: AvaliacaoRoute,
  ComunidadeRoute: ComunidadeRoute,
  DashboardRoute: DashboardRoute,
  DepoimentoRoute: DepoimentoRoute,
  LeituraTrajetoriaRoute: LeituraTrajetoriaRoute,
  LeituraTrajetoriaOfertaRoute: LeituraTrajetoriaOfertaRoute,
  LoginRoute: LoginRoute,
  PosCompraRoute: PosCompraRoute,
  RelatorioOnlineRoute: RelatorioOnlineRoute,
  RelatorioPdfRoute: RelatorioPdfRoute,
  CheckoutOfferIdRoute: CheckoutOfferIdRoute,
  ContaRoute: ContaRoute,
  ConteudosRoute: ConteudosRoute,
  VideosRoute: VideosRoute,
  SobreRoute: SobreRoute,
  AjudaRoute: AjudaRoute,
  PropositoRoute: PropositoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
